# Generated by Django 4.2.28 on 2026-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_device',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
