# Generated by Django 4.2.28 on 2026-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notify_election_close',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='notify_election_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='notify_election_results',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
