"""
Django settings for securevoter project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# securevoter/settings.py
from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv


# BASE DIRECTORY 
BASE_DIR = Path(__file__).resolve().parent.parent


#  LOAD ENVIRONMENT VARIABLES 
load_dotenv(BASE_DIR / ".env")


#  SECURITY SETTINGS 
SECRET_KEY    = os.getenv("DJANGO_SECRET_KEY", "unsafe-dev-key")
DEBUG         = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS", "").split(",")
    if os.getenv("ALLOWED_HOSTS")
    else []
)


#  APPLICATIONS 
INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',

    # Local apps
    'core',
    'voter_dashboard',
    'admin_dashboard',
]


#  MIDDLEWARE 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


#  ROOT URL CONFIGURATION 
ROOT_URLCONF = 'securevoter.urls'


#  TEMPLATES 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],  # Global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'securevoter.wsgi.application'


# DATABASE 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME':   BASE_DIR / 'db.sqlite3',
    }
}


# PASSWORD VALIDATORS 
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


#  INTERNATIONALIZATION 
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'Asia/Kathmandu'
USE_I18N      = True
USE_TZ        = True



# settings.py
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # collectstatic destination — never serve this in dev

STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
    BASE_DIR / 'voter_dashboard' / 'static',
    BASE_DIR / 'admin_dashboard' / 'static',
]


#  MEDIA FILES (candidate photos, uploads) 
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'candidate_photos'


# DEFAULT AUTO FIELD 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CUSTOM USER MODEL 
AUTH_USER_MODEL = 'core.Student'


#  DJANGO REST FRAMEWORK 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}


#  SIMPLE JWT 
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS':  False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


#  VOTE ENCRYPTION KEY 
VOTE_ENCRYPTION_KEY = os.getenv("VOTE_ENCRYPTION_KEY")
if not VOTE_ENCRYPTION_KEY:
    print("WARNING: VOTE_ENCRYPTION_KEY is not set in .env. Vote encryption will fail!")