# Generated by Django 4.2.28 on 2026-04-07 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voter_dashboard', '0001_initial'),
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='voter_dashboard.election'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electionlog',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter_dashboard.election'),
        ),
    ]
