# Generated by Django 4.2.28 on 2026-03-12 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voter_dashboard', '0001_initial'),
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraudalert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='fraudalert',
            old_name='resolved',
            new_name='reviewed',
        ),
        migrations.RemoveField(
            model_name='fraudalert',
            name='student',
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='alert_type',
            field=models.CharField(choices=[('face_mismatch', 'Face Mismatch'), ('spoof_attempt', 'Spoof Attempt'), ('too_many_attempts', 'Too Many Attempts'), ('multiple_faces', 'Multiple Faces'), ('unknown_device', 'Unknown Device')], default='face_mismatch', max_length=30),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='voter_dashboard.election'),
        ),
    ]
